[General]
Description=Material You inspired colors
Name=Material You

[ColorScheme]
active_colors=#fff1f1f1, #ff0e0e0e, #ffD7D7D7, #ffB8B8B8, #ffE4E4E4, #ffEDEDED, #fff1f1f1, #fff1f1f1, #fff1f1f1, #ff0e0e0e, #ff0e0e0e, #fff1f1f1, #ffE4E4E4, #fff1f1f1, #ffD7D7D7, #ffC8C8C8, #ffD7D7D7, #ff0e0e0e, #ff0e0e0e, #fff1f1f1, #ff0e0e0e
disabled_colors=#ffa8a8a8, #ff0e0e0e, #ffD7D7D7, #ffB8B8B8, #ffE4E4E4, #ffEDEDED, #ffa8a8a8, #ffa8a8a8, #ffa8a8a8, #ffa8a8a8, #ff0e0e0e, #fff1f1f1, #ffE4E4E4, #ffa8a8a8, #ffD7D7D7, #ffC8C8C8, #ffD7D7D7, #ff0e0e0e, #ff0e0e0e, #ffa8a8a8, #ff0e0e0e
inactive_colors=#fff1f1f1, #ff0e0e0e, #ffD7D7D7, #ffB8B8B8, #ffE4E4E4, #ffEDEDED, #fff1f1f1, #fff1f1f1, #fff1f1f1, #ff0e0e0e, #ff0e0e0e, #fff1f1f1, #ffE4E4E4, #fff1f1f1, #ffD7D7D7, #ffC8C8C8, #ffD7D7D7, #ff0e0e0e, #ff0e0e0e, #fff1f1f1, #ff0e0e0e
