[config]
version_check = false

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-step", "100", "--transition-fps", "120", "--transition-type", "grow", "--transition-angle", "30", "--transition-duration", "1"]

[templates.m3colors]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.local/state/quickshell/user/generated/colors.json'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland/colors.conf'
output_path = '~/.config/hypr/hyprland/colors.conf'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprland/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel/fuzzel.ini'
output_path = '~/.config/fuzzel/fuzzel.ini'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'


[templates.discord]
input_path = "~/.config/matugen/templates/apps/discord.css"
output_path = "~/.config/vesktop/themes/HyprNoon.css"

# [templates.obsidian]
# input_path = "~/.config/matugen/templates/apps/obsidian.css"
# output_path = "/mnt/Data/General-Archive/obsidian/.obsidian/snippets/HyprNoon.css"

[templates.vscode]
input_path = "~/.config/matugen/templates/apps/vscode-color-theme.json"
output_path = "~/.windsurf/extensions/hyprnoon/themes/vscode.json"

[templates.pywalfox]
input_path = '~/.config/matugen/templates/apps/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'
