[config]
version_check = false

[config.wallpaper]
command = "swww"
arguments = [
    "img",
    "--transition-step",
    "100",
    "--transition-fps",
    "120",
    "--transition-type",
    "grow",
    "--transition-angle",
    "30",
    "--transition-duration",
    "1"
]

[templates.m3colors]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.local/state/quickshell/user/generated/colors.json'

[templates.terminal_sequences]
input_path = '~/.config/matugen/templates/terminal/sequences.txt'
output_path = '~/.local/state/quickshell/user/generated/terminal/sequences.txt'
post_hook = '''
sequences=$(cat ~/.local/state/quickshell/user/generated/terminal/sequences.txt | tr -d '\n')
for pid in $(pgrep fish); do
    echo -en "$sequences" > /proc/$pid/fd/1 2>/dev/null || true
done
'''

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'
post_hook = "starship init zsh > ~/.zshrc"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland/colors.conf'
output_path = '~/.config/hypr/hyprland/colors.conf'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprland/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel/fuzzel.ini'
output_path = '~/.config/fuzzel/fuzzel.ini'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
pre_hook = 'rm -rf ~/.config/gtk-4.0 && mkdir -p ~/.config/gtk-4.0'
input_path = '~/.config/matugen/templates/gtk/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/applications/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.qt6ct]
input_path = "~/.config/matugen/templates/qtct-colors.conf"
output_path = "~/.config/qt6ct/colors/matugen.conf"
post_hook = 'ratbagctl "Logitech G102 LIGHTSYNC Gaming Mouse" led 0 set color "{{colors.primary_container.default.hex_stripped}}" &'

[templates.cursor]
input_path = "~/.config/matugen/templates/applications/vscode-color-theme.json"
output_path = "~/.config/cursor/user/settings.json"
post_hook = '''
(
THEME_DIR="$HOME/.config/cursor/extensions/material-you-theme"
mkdir -p "$THEME_DIR/themes"
cp "$HOME/.config/cursor/user/settings.json" "$THEME_DIR/themes/material-you-color-theme.json"

cat > "$THEME_DIR/package.json" << 'EOF'
{
    "name": "material-you-theme",
    "displayName": "Material You Theme",
    "version": "1.0.0",
    "engines": {"vscode": "*"},
    "categories": ["Themes"],
    "contributes": {
        "themes": [{
            "label": "Material You",
            "uiTheme": "vs-dark",
            "path": "./themes/material-you-color-theme.json"
        }]
    }
}
EOF

) &
'''

[templates.heroic]
input_path = "~/.config/matugen/templates/applications/heroic-theme.css"
output_path = "~/.cache/quickshell/user/generated/heroic-colors.css"

[templates.Telegram]
input_path = "~/.config/matugen/templates/applications/telegram-colors.tdesktop-theme"
output_path = "~/.config/telegram-desktop/themes/material-you.tdesktop-theme"

[templates.spicetify]
input_path = "~/.config/matugen/templates/applications/colors.ini"
output_path = "~/.config/spicetify/Themes/Comfy/color.ini"
post_hook = "spicetify config current_theme Comfy && pgrep -x spotify >/dev/null && spicetify apply & disown"

[templates.discord]
input_path = "~/.config/matugen/templates/applications/discord.css"
output_path = "~/.config/vesktop/themes/HyprNoon.css"

[templates.obsidian]
input_path = "~/.config/matugen/templates/applications/obsidian.css"
output_path = "/run/media/pc/Data/General-Archive/obsidian/.obsidian/snippets/HyprNoon.css"
