exec = export SLURP_ARGS='-d -c DFE3FBBB -b 44485B44 -s 00000000'

general {
    col.active_border = rgb(B6C4FF) rgb(121318)
    col.inactive_border = rgb(90909A)
}

misc {
    background_color = rgba(121318FF)
}

windowrulev2 = bordercolor rgba(B6C4FFAA) rgba(B6C4FF77),pinned:1
