# exec = export SLURP_ARGS='-d -c F9DCB5BB -b 57432744 -s 00000000'

general {
    col.active_border =  rgb(F2BE70) rgb(0,0,0)
    col.inactive_border = rgba(9C8F7F30)
}

misc {
    background_color = rgba(17130EFF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(17130EFF)
        col.text = rgba(EBE1D8FF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(EBE1D8), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(EBE1D8), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(EBE1D8), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrulev2 = bordercolor rgba(F2BE70AA) rgba(F2BE7077),pinned:1
