### This file supports bash-style comments, and blank lines.
### PKGs on same line will be sent to `yay` together, unless `-f` is specified.

### Most dependencies have been moved to meta packages as declared in arch-packages.
### Use this file for declaring extra dependencies which you need but are not declared by default.
heroic-games-launcher-bin nwg-look zen-browser-bin zed windsurf vesktop qt5ct qt6ct matugen-bin ttf-jetbrains-mono ttc-iosevka hyprshade obsidian telegram-desktop spotify-launcher spicetify-marketplace-bin python-pywalfox kvantum kvantum-qt5 uwsm stow timeshift
